rm -rf ./result/maxval/.svn
rm -rf ./result/.svn
rm -rf ./input/sp_graph/.svn
rm -rf ./input/maxval_graph/.svn
rm -rf ./input/.svn
rm -rf ./bin/.svn
rm -rf ./src/client/.svn
rm -rf ./src/worker/.svn
rm -rf ./src/external/google-flags/gflags/.svn
rm -rf ./src/external/google-flags/CMakeFiles/gflags.dir/.svn
rm -rf ./src/external/google-flags/CMakeFiles/.svn
rm -rf ./src/external/google-flags/google/.svn
rm -rf ./src/external/google-flags/.svn
rm -rf ./src/external/google-logging/glog/.svn
rm -rf ./src/external/google-logging/CMakeFiles/glog.dir/.svn
rm -rf ./src/external/google-logging/CMakeFiles/.svn
rm -rf ./src/external/google-logging/base/.svn
rm -rf ./src/external/google-logging/.svn
rm -rf ./src/external/.svn
rm -rf ./src/external/webgraph/CMakeFiles/webgraph.dir/.svn
rm -rf ./src/external/webgraph/CMakeFiles/.svn
rm -rf ./src/external/webgraph/.svn
rm -rf ./src/kernel/.svn
rm -rf ./src/examples/.svn
rm -rf ./src/.svn
rm -rf ./src/master/.svn
rm -rf ./src/util/.svn
rm -rf ./fpga/obj/.svn
rm -rf ./fpga/bin/.svn
rm -rf ./fpga/src/.svn
rm -rf ./fpga/.svn
rm -rf ./conf/.svn
rm -rf ./cmake/.svn
rm -rf ./logs/.svn
