# TCL File Generated by Component Editor 12.0
# Sat Nov 03 18:27:23 EDT 2012
# DO NOT MODIFY


# 
# dram_read "dram_read" v1.0
# null 2012.11.03.18:27:23
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module dram_read
# 
set_module_property NAME dram_read
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME dram_read
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dram_read
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dram_read.v VERILOG PATH dram_read.v


# 
# parameters
# 
add_parameter DDR_BASE STD_LOGIC_VECTOR 1073741824
set_parameter_property DDR_BASE DEFAULT_VALUE 1073741824
set_parameter_property DDR_BASE DISPLAY_NAME DDR_BASE
set_parameter_property DDR_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property DDR_BASE UNITS None
set_parameter_property DDR_BASE ALLOWED_RANGES 0:1073741824
add_parameter ADDRESS_WIDTH INTEGER 32
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
add_parameter TOTAL_DATA INTEGER 8
set_parameter_property TOTAL_DATA DEFAULT_VALUE 8
set_parameter_property TOTAL_DATA DISPLAY_NAME TOTAL_DATA
set_parameter_property TOTAL_DATA TYPE INTEGER
set_parameter_property TOTAL_DATA UNITS None
set_parameter_property TOTAL_DATA ALLOWED_RANGES -2147483648:2147483647


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point dram_flush
# 
add_interface dram_flush conduit end
set_interface_property dram_flush associatedClock ""
set_interface_property dram_flush associatedReset ""
set_interface_property dram_flush ENABLED true

add_interface_port dram_flush dram_flush export Input 1


# 
# connection point dram_rd_user
# 
add_interface dram_rd_user conduit end
set_interface_property dram_rd_user associatedClock clock
set_interface_property dram_rd_user associatedReset reset
set_interface_property dram_rd_user ENABLED true

add_interface_port dram_rd_user user_read_buffer export Output 1
add_interface_port dram_rd_user user_buffer_output_data export Input 256
add_interface_port dram_rd_user user_data_available export Input 1


# 
# connection point dram_rd_control
# 
add_interface dram_rd_control conduit end
set_interface_property dram_rd_control associatedClock clock
set_interface_property dram_rd_control associatedReset reset
set_interface_property dram_rd_control ENABLED true

add_interface_port dram_rd_control control_fixed_location export Output 1
add_interface_port dram_rd_control control_read_base export Output 31
add_interface_port dram_rd_control control_read_length export Output 31
add_interface_port dram_rd_control control_go export Output 1
add_interface_port dram_rd_control control_done export Input 1


# 
# connection point dram_rd_fifo
# 
add_interface dram_rd_fifo conduit end
set_interface_property dram_rd_fifo associatedClock clock
set_interface_property dram_rd_fifo associatedReset ""
set_interface_property dram_rd_fifo ENABLED true

add_interface_port dram_rd_fifo dram_fifo_readdata export Output 64
add_interface_port dram_rd_fifo dram_fifo_read export Input 1
add_interface_port dram_rd_fifo dram_fifo_empty export Output 1


# 
# connection point num_keys
# 
add_interface num_keys conduit end
set_interface_property num_keys associatedClock clock
set_interface_property num_keys associatedReset ""
set_interface_property num_keys ENABLED true

add_interface_port num_keys num_keys export Input 32

