# TCL File Generated by Component Editor 12.0
# Mon Sep 10 16:03:27 EDT 2012
# DO NOT MODIFY


# 
# dram_write "dram_write" v1.0
# null 2012.09.10.16:03:27
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module dram_write
# 
set_module_property NAME dram_write
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME dram_write
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dram_write
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dram_write.v VERILOG PATH dram_write.v


# 
# parameters
# 
add_parameter DDR_BASE STD_LOGIC_VECTOR 1073741824
set_parameter_property DDR_BASE DEFAULT_VALUE 1073741824
set_parameter_property DDR_BASE DISPLAY_NAME DDR_BASE
set_parameter_property DDR_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property DDR_BASE UNITS None
set_parameter_property DDR_BASE ALLOWED_RANGES 0:1073741824
set_parameter_property DDR_BASE HDL_PARAMETER true

add_parameter ADDRESS_WIDTH INTEGER 32
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point dram_wr_fifo
# 
add_interface dram_wr_fifo conduit end
set_interface_property dram_wr_fifo associatedClock clock
set_interface_property dram_wr_fifo associatedReset ""
set_interface_property dram_wr_fifo ENABLED true

add_interface_port dram_wr_fifo dram_fifo_writedata export Input 64
add_interface_port dram_wr_fifo dram_fifo_write export Input 1
add_interface_port dram_wr_fifo dram_fifo_full export Output 1


# 
# connection point dram_wr_control
# 
add_interface dram_wr_control conduit end
set_interface_property dram_wr_control associatedClock clock
set_interface_property dram_wr_control associatedReset reset
set_interface_property dram_wr_control ENABLED true

add_interface_port dram_wr_control control_fixed_location export Output 1
add_interface_port dram_wr_control control_write_base export Output 31
add_interface_port dram_wr_control control_write_length export Output 31
add_interface_port dram_wr_control control_go export Output 1
add_interface_port dram_wr_control control_done export Input 1


# 
# connection point dram_wr_user
# 
add_interface dram_wr_user conduit end
set_interface_property dram_wr_user associatedClock clock
set_interface_property dram_wr_user associatedReset reset
set_interface_property dram_wr_user ENABLED true

add_interface_port dram_wr_user user_write_buffer export Output 1
add_interface_port dram_wr_user user_buffer_input_data export Output 256
add_interface_port dram_wr_user user_buffer_full export Input 1

